<a href="https://colab.research.google.com/github/Nimira43/DarthNimira/blob/master/00_tensorflowfund.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# fundamentals of tensors in tensorflow

#intro to tensors, getting info from tensors, manipulating tensors, numpy, using @t.function to speed things up, use TPU's.

In [1]:
import tensorflow as tf # import tensorflow
print(tf.__version__)

2.9.2


In [2]:
scalar = tf.constant(7) # create tensors with tf.constant()
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
 scalar.ndim # check number of dimension of a tensor (ndim stands for number of dimensions)

0

In [4]:
vector = tf.constant([10, 10]) # create a vector
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim # check dimensions of vector

1

In [6]:
matrix = tf.constant([[10, 7],
                      [7,10]]) # create matrix (more than 1 dimension)
                      

In [7]:
matrix.ndim

2

In [8]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # another matrix with specified datatype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

scalar - single number

vector - a number with direction (like wind speed and direction)

matrix - 2 dimensional array

tensor - an n dimensional array of number

creating tensors with tf.Variable