<a href="https://colab.research.google.com/github/Nimira43/DarthNimira/blob/master/00_tensorflowfund.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# fundamentals of tensors in tensorflow

#intro to tensors, getting info from tensors, manipulating tensors, numpy, using @t.function to speed things up, use TPU's.

In [1]:
import tensorflow as tf # import tensorflow
print(tf.__version__)

2.9.2


In [2]:
scalar = tf.constant(7) # create tensors with tf.constant()
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
 scalar.ndim # check number of dimension of a tensor (ndim stands for number of dimensions)

0

In [4]:
vector = tf.constant([10, 10]) # create a vector
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim # check dimensions of vector

1

In [6]:
matrix = tf.constant([[10, 7],
                      [7,10]]) # create matrix (more than 1 dimension)
                      

In [7]:
matrix.ndim

2

In [8]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # another matrix with specified datatype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

scalar - single number

vector - a number with direction (like wind speed and direction)

matrix - 2 dimensional array

tensor - an n dimensional array of number

creating tensors with tf.Variable

In [13]:
changeable_tensor = tf.Variable([10 , 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

change an element in changeable tensor

In [14]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

creating random tensors

In [20]:
random_1 = tf.random.Generator.from_seed(42) # first random tensor (but same) and = set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2 # are they equal?

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

the output above is dictated by the seed value

shuffle the order of elements in a tensor to scramble list of data

In [25]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
tf.random.shuffle(not_shuffled) # shuffle non-shuffled tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [26]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [32]:
tf.random.set_seed(42) # global seed
tf.random.shuffle(not_shuffled, seed=42) # operational seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

random3 = tf.random.Generator.from_seed(7)
random3 = random3.normal(shape=(3, 2))

random3



In [42]:
random3 = tf.random.Generator.from_seed(27)
random3 = random3.normal(shape=(8, 6, 7, 4))

random3

<tf.Tensor: shape=(8, 6, 7, 4), dtype=float32, numpy=
array([[[[-1.2060374 ,  0.8307429 ,  1.0951619 ,  1.3672234 ],
         [-0.54532146,  1.9302735 , -0.3151453 , -0.8761205 ],
         [-2.7316678 , -0.15730922,  1.3692921 , -0.4367834 ],
         ...,
         [ 1.2232229 , -1.8653691 ,  0.00511209, -1.0493753 ],
         [ 0.7901182 ,  1.585549  ,  0.4356279 ,  0.23645182],
         [-0.1589871 ,  1.302304  ,  0.9592239 ,  0.85874265]],

        [[-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174],
         [ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 ],
         [-0.645002  ,  0.18022095, -0.14656258,  0.34374258],
         ...,
         [ 0.20386009,  0.562024  , -2.3001142 , -1.349454  ],
         [ 0.81485   ,  1.2790666 ,  0.02203509,  1.5428121 ],
         [ 0.78953624,  0.53897345, -0.48535708,  0.74055266]],

        [[ 0.31662667, -1.4391748 ,  0.58923835, -1.4268045 ],
         [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
         [-0.23193763, -1.810785

In [43]:
tf.random.set_seed(11)
tf.random.shuffle(random3, seed=4)

<tf.Tensor: shape=(8, 6, 7, 4), dtype=float32, numpy=
array([[[[ 1.493164  , -0.28871155,  0.31284064,  1.663845  ],
         [-1.028107  , -0.60134953,  0.455365  ,  0.18552932],
         [-2.0545108 , -1.7917832 , -0.781357  ,  1.7088543 ],
         ...,
         [ 0.89297235,  1.5463222 , -0.8302462 , -1.4948393 ],
         [ 0.38628715, -1.2676666 ,  0.12750275,  0.12517293],
         [ 0.3160493 , -1.3636322 ,  0.5770591 ,  0.30280197]],

        [[-3.3228774 , -0.27568147,  0.24829084, -0.90035295],
         [-2.2462475 , -0.45878425, -1.9838426 ,  1.0531965 ],
         [ 0.16383527,  0.08420128, -0.35761365,  0.52944607],
         ...,
         [ 1.4299089 ,  1.1519113 ,  2.4963074 ,  0.7028313 ],
         [-0.638703  ,  1.2545483 ,  0.15263537, -0.38345093],
         [-0.1335102 ,  0.17139332, -0.21565591, -0.06827872]],

        [[ 0.30605847, -0.7204267 ,  0.0638603 ,  0.749325  ],
         [ 0.87557787,  1.3275943 , -0.79108816,  1.4859759 ],
         [ 1.8666607 ,  0.753329

other ways to make tensors

In [44]:
tf.ones([10, 7]) # create tensor of all ones

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [48]:
tf.zeros(shape=(3, 4)) # all zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

you can turn numpy arrays into tensorflow tensors

In [49]:
import numpy as np
numpy_A = np.arange(1 ,25, dtype=np.int32) # create numpy arrary between 1 and 25
numpy_A

# X = tf.constant(some_matrix)         capital for matrix or tensor
# y = tf.constant(vector)              non-capital for vector



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

then convert into a tensor

In [50]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

change the shape of the numpy arrary

In [58]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
C = tf.constant(numpy_A, shape=(3, 4, 2))
D = tf.constant(numpy_A, shape=(2, 2, 3, 2))
E = tf.constant(numpy_A, shape=(2, 2, 2, 3))
F = tf.constant(numpy_A, shape=(2, 12))
A, B, C, D, E, F

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8]],
 
        [[ 9, 10],
         [11, 12],
         [13, 14],
         [15, 16]],
 
        [[17, 18],
         [19, 20],
         [21, 22],
         [23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
 array([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],
 
         [[ 7,  8],
          [ 9, 10],
          [11, 12]]],
 
 
        [[[13, 14],
          [15, 16],
          [17, 18]],
 
         [[19, 20],
          [21, 22],
        

getting info about tensors

such as these attributes =

shape

rank

axis or dimension

size

In [59]:
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5)) # create a rank 4 tensor - four dimensions
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [60]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [61]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

get various attributes of our tensor

In [65]:
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along 0 axis: ", rank_4_tensor.shape[0])
print("Elements along last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in tensor (as numpy): ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along 0 axis:  2
Elements along last axis:  5
Total number of elements in tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in tensor (as numpy):  120
