<a href="https://colab.research.google.com/github/Nimira43/DarthNimira/blob/master/01_tensorflowfund.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
matrix1 = tf.constant([[7, 4, 3],
                       [5, 4, 9],
                       [3, 8, 6]])
matrix1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 4, 3],
       [5, 4, 9],
       [3, 8, 6]], dtype=int32)>

In [3]:
matrix2 = tf.constant([[8, 5],
                       [6, 9],
                       [2, 7]])
matrix2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[8, 5],
       [6, 9],
       [2, 7]], dtype=int32)>

In [4]:
matrix3 = tf.constant([[5, 1, 7],
                       [6, 4, 8],
                       [3, 9, 2]])
matrix3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[5, 1, 7],
       [6, 4, 8],
       [3, 9, 2]], dtype=int32)>

In [5]:
matrix4 = tf.constant([[5, 7],
                       [8, 4],
                       [6, 1]])
matrix4

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 7],
       [8, 4],
       [6, 1]], dtype=int32)>

In [7]:
tf.matmul(matrix1, matrix2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 86,  92],
       [ 82, 124],
       [ 84, 129]], dtype=int32)>

In [8]:
tf.matmul(matrix3, matrix4)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 75,  46],
       [110,  66],
       [ 99,  59]], dtype=int32)>

In [9]:
tf.matmul(matrix1, matrix3)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 68,  50,  87],
       [ 76, 102,  85],
       [ 81,  89,  97]], dtype=int32)>

In [10]:
tf.matmul(matrix2, matrix4)

InvalidArgumentError: ignored

In [11]:
matrix2, tf.reshape(matrix4, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[8, 5],
        [6, 9],
        [2, 7]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[5, 7, 8],
        [4, 6, 1]], dtype=int32)>)

In [12]:
tf.matmul(matrix2, tf.reshape(matrix4, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[60, 86, 69],
       [66, 96, 57],
       [38, 56, 23]], dtype=int32)>

In [13]:
tf.reshape(matrix2, shape=(2, 3)), matrix4

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[8, 5, 6],
        [9, 2, 7]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[5, 7],
        [8, 4],
        [6, 1]], dtype=int32)>)

In [14]:
tf.matmul((tf.reshape(matrix2, shape=(2, 3))), matrix4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[116,  82],
       [103,  78]], dtype=int32)>

TRANSPOSE

In [16]:
matrix2, tf.transpose(matrix2), tf.reshape(matrix2, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[8, 5],
        [6, 9],
        [2, 7]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[8, 6, 2],
        [5, 9, 7]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[8, 5, 6],
        [9, 2, 7]], dtype=int32)>)

In [17]:
matrix4, tf.transpose(matrix4), tf.reshape(matrix4, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[5, 7],
        [8, 4],
        [6, 1]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[5, 8, 6],
        [7, 4, 1]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[5, 7, 8],
        [4, 6, 1]], dtype=int32)>)

In [19]:
tf.transpose(matrix2), matrix4

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[8, 6, 2],
        [5, 9, 7]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[5, 7],
        [8, 4],
        [6, 1]], dtype=int32)>)

In [18]:
tf.matmul(tf.transpose(matrix2), matrix4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  82],
       [139,  78]], dtype=int32)>

In [20]:
matrix2, tf.transpose(matrix4)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[8, 5],
        [6, 9],
        [2, 7]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[5, 8, 6],
        [7, 4, 1]], dtype=int32)>)

In [21]:
tf.matmul(matrix2, tf.transpose(matrix4))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[75, 84, 53],
       [93, 84, 45],
       [59, 44, 19]], dtype=int32)>

In [22]:
tf.matmul(matrix2, tf.reshape(matrix4, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[60, 86, 69],
       [66, 96, 57],
       [38, 56, 23]], dtype=int32)>